### ISSUE TITLE
Die after entering portal

### ISSUE THREAD

**Issue by BrendanSaywell** [KyaniteMods/DeeperAndDarker#145]
**Mod Version**: 1.1.6

**Mod Loader**: fabric

**Description**:
The portal can spawn in the void, instantly killing you when you enter the dimension.

**To Reproduce**:
1. Go through portal

**Comment by Amsur** [comment]
Same, i'm playing with the modpack "better minecraft" on 1.19.2 wich use deeper and darker 1.1.6

the portal is at -35 in altitude in the overworld and when I enter in the otherside I spawn under the bedrock.

**Comment by Pedro270707** [comment]
I am not spawning in the void, so probably fixed?

**Comment by Pedro270707** [comment]
Bug is still in the game for 1.19.2

**Comment by Pedro270707** [comment]
Fixed in 1.2.2

**Comment by LemonPAKA** [comment]
![{0CB1810F-A5FD-4330-D73C-9FE45DC3F69E}](https://github.com/KyaniteMods/DeeperAndDarker/assets/17202894/6b77ce2f-49d1-43c5-bdcf-99cde1bd8fda)
Entering portal and instantly kill you in the void
version 1.2.3(tried to delete dimensions(otherside) files and update to 1.2.5 but still not work)
prominence II 2.6.0 modpack (world origin generated on 2.5.0)
world seed is 5506523918394750547
world level type is default
portal waypoint 3697 -35 -548

**Comment by vbaier** [comment]
@NewJumper @Pedro270707 I am also seeing this behavior similar to LemonPAKA in the Vshojo modpack. I also tried deleting the dimension folder and restarting to no avail. Checking in creative mode I am clearly spawning under bedrock. I've also tried creating a new portal in creative mode in the event it would generate a better portal location in otherside, but I still spawn under bedrock. I am currently running version 1.2.5 on a fabric server version 1.20.1.

Unfortunately I don't have a perfect pedigree of my world file. Is this a known issue? If not is there some NBT data I can examine as a possible workaround?
